### ISSUE TITLE
PATCH returns response code 0 finishing upload

### ISSUE THREAD

**Issue by kirk-marple** [tusdotnet/tusdotnet#175]
I'm seeing a strange issue when uploading 1K+ files via Uppy to our Tus server.  (Using tusdotnet nuget 2.6.0.)

There's four files, and it seems reproducible, which don't finish.  I can see this request in our log, but none of our Tus store code after it.  It's like the middleware skips the Tus store altogether in these specific cases.

<img width="709" alt="175161912-79dcee8e-b9c2-4b63-9829-5e33c843387e" src="https://user-images.githubusercontent.com/13594550/175162626-1b90f365-5abd-49e4-a482-e8b67cc494f8.png">

And this is what I'm seeing in the browser dev tools.

<img width="533" alt="image" src="https://user-images.githubusercontent.com/13594550/175162012-ff545b34-c566-4d48-8e1f-746379a013a5.png">

The HEAD call right before this looks to work fine, and the remaining bytes in the logs matches what's being sent in the PATCH.

<img width="709" alt="Screenshot 2022-06-22 151957" src="https://user-images.githubusercontent.com/13594550/175163003-b253f604-36ac-465d-b294-9a6ecb25a4eb.png">

<img width="454" alt="image" src="https://user-images.githubusercontent.com/13594550/175163227-dca95040-d5db-456d-8aa4-2347b2e806fd.png">

Any ideas what to look at to debug this?

**Comment by smatsson** [comment]
That's a weirdly interesting and annoying issue :) 

Do the files differ in any way? Size, type etc? Do the files always fail at the same offset? Does it matter what chunk size you use on the client? Are there any events in your tusdotnet setup that fails the request for some reason? 

What is your infrastructure setup? As you probably already know, status code 0 is usually not something received from a server but rather the indication that nothing was received (e.g. timeout). Is the log coming from your actual backend or from some type of load balancer/firewall/reverse proxy? 

> Any ideas what to look at to debug this?

1. I would start with adding additional logging in your backend code to make sure that the request actually hits the backend and is not intercepted and dropped by some load balancer/firewall/proxy. 
2. Step two would be to add logging in the `OnAuthorizeAsync` event to check if tusdotnet determined it to be a valid tus request
3. Record the response from tusdotnet and log it to make sure that the response is not dropped.

Hacky code that does the above:
```csharp
using tusdotnet;
using tusdotnet.Models;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddLogging();

var app = builder.Build();

app.Use(async (httpContext, next) =>
{
    try
    {
        GetLogger(httpContext).LogInformation($"Got request {httpContext.Request.Method} {httpContext.Request.Path}");

        using var ms = new MemoryStream();
        var responseStream = httpContext.Response.Body;
        httpContext.Response.Body = ms;

        await next();

        ms.Seek(0, SeekOrigin.Begin);
        using var streamReader = new StreamReader(ms);
        string responseString = streamReader.ReadToEnd();

        GetLogger(httpContext).LogInformation($"Response for {httpContext.Request.Method} {httpContext.Request.Path}: {httpContext.Response.StatusCode} -> {responseString}");

        ms.Seek(0, SeekOrigin.Begin);
        ms.CopyTo(responseStream);

    }
    catch (Exception ex)
    {
        GetLogger(httpContext).LogInformation(ex, $"Exception for request {httpContext.Request.Method} {httpContext.Request.Path}");
    }
});

app.UseTus(httpContext => new tusdotnet.Models.DefaultTusConfiguration
{
    // Rest of setup omitted
    Events = new()
    {
        OnAuthorizeAsync = eventcontext =>
        {
            if (eventcontext.Intent != IntentType.WriteFile)
                return Task.CompletedTask;

            GetLogger(eventcontext.HttpContext).LogInformation($"OnAuthorize for {eventcontext.FileId}");
            return Task.CompletedTask;
        }
    }
});

app.Use((httpContext, next) =>
{
    GetLogger(httpContext).LogInformation($"Request for {httpContext.Request.Method} {httpContext.Request.Path} was ignored by tusdotnet");
    return next();
});

static ILogger GetLogger(HttpContext context) => context.RequestServices.GetRequiredService<ILogger>();
```

If `$"Exception for request {httpContext.Request.Method} {httpContext.Request.Path}"` is not logged I would start investigating why the request does not hit the backend.

If `$"OnAuthorize for {eventcontext.FileId}"` is not logged I would investigate why the request is not determined to be valid (let me know and I'll help you debug)

If `$"Request for {httpContext.Request.Method} {httpContext.Request.Path} was ignored by tusdotnet"` _is_ logged I would investigate why the request is not considered valid by tusdotnet (same as the above basically)

Check `Response for ...` and see what, if any, response is logged.

Check `Exception for request ...` and see what, if any exception is logged.

Hope this help you get started. It's vacation time here so pardon the late reply.

**Comment by kirk-marple** [comment]
@smatsson Sorry for the slow response, got caught up with a million things and just getting back to this.

We're deployed on Azure App Service, to your one question.

It's always with these same four files, so it may be something with their specific file sizes, I'm guessing.

It is getting into ITusStore.AppendDataAsync, but isn't able to read anything from the incoming HTTP stream.

In the browser I get the error:
```
https://tus-perf.unstruk.io/api/v1/tus/ae16ab681fad4a4fa20ff49d952b6337

Error: tus: failed to upload chunk at offset 6451750, caused by [object ProgressEvent], originated from request (method: PATCH, url: https://tus-perf.unstruk.io/api/v1/tus/ae16ab6…, response code: n/a, response text: n/a, request id: n/a)
    at o.value (upload.js:414:23)
    at upload.js:728:16
```

It only seems to happen on these files, but there should be 1154492 bytes left to upload (for example).

Maybe it's an Uppy problem in how they're uploading?

Here's the steps I see in my server logs:
![image](https://user-images.githubusercontent.com/13594550/182090081-f5c7efd7-e05d-466b-ad2f-ca7f6800e8a5.png)

**Comment by smatsson** [comment]
>Sorry for the slow response, got caught up with a million things and just getting back to this.

Welcome to IT :) The same happened to me so pardon my late reply...

> response code: n/a, response text: n/a, request id: n/a

I would say that this indicates a timeout of some sort as there is no response from the server. `Recognized zero bytes copied...` would indicate that nothing was read from the client but if so, the client would have gotten a reply back (or at least I would assume so). My first guess would be request buffering in the reverse proxy (most likely IIS if on Windows app services, or Nginx/YARP if on Linux). That is however contradicted by the fact that the request actually hits your code as, at least traditionally, request buffering buffers the entire request (both headers + body) before sending it upstream. It also seems weird that only a few files are affected.

It's possible that Uppy does something off but I find it unlikely since it's built by Transloadit, the same people who invented tus.  

I would test the following an see if there is any progress:
* Change the [chunk size](https://uppy.io/docs/tus/#chunkSize-Infinity) in Uppy to something very small (say a few KB) and see if it that data is transferred.
* Switch tusdotnet to use pipelines instead of streams. Pipelines is available on .NET Core 3.1+ and is enabled by setting `UsePipelinesIfAvailable` to true in the `DefaultTusConfiguration`. As pipelines are more efficient than streams it might be that more data is saved.

**Comment by smatsson** [comment]
Any progress on this?

**Comment by smatsson** [comment]
Closing due to inactivity
