### ISSUE TITLE
(500) Internal server error on deleting files

### ISSUE THREAD

**Issue by Unthred** [tusdotnet/tusdotnet#67]
I am unable to delete the 6 files that tus creates when for each uploaded file.
I am pretty much using the TusClient and TusHttpClient from Tus.io

On the odd occasion it does actually delete the files but 95% of the time I get an internal server error.

2019-07-30 12:15:54.1926 ERROR [8:] TusFileTransferClient.TusHttpClient.PerformRequest TusException : TusFileTransferClient.TusException: The remote server returned an error: (500) Internal Server Error. ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()

````
var file = new FileInfo(filename);
var client = new TusClient();
var metaData = new Dictionary<string, string>
{
   {"product", _fileRetrievalInfo.DisplayName},
   {"fileType", _fileRetrievalInfo.RetrievalType.ToString()}, 
   {"id", _surveyor.Id.ToString()}
};
var fileUrl = client.Create(uploadAddress, file, metaData);
client.Upload(fileUrl, file);
client.Delete(fileUrl));
''''

**Comment by smatsson** [comment]
Hi!

What does the server log say? Any exception thrown?

**Comment by Unthred** [comment]
Does Tus have its own log? I have looked in my app log and cannot find anything
I have also looked in the machines event logs and found nothing there either.
Is there a way to configure Tus logging?

thanks

**Comment by smatsson** [comment]
tusdotnet does not have its own log but since a `500 internal server` error was returned, my guess is that an exception was thrown and tusdotnet just passes all exceptions to the web app so that it can pick it up and log it. Here's a simple example on how the test sites does it: https://github.com/tusdotnet/tusdotnet/blob/master/Source/TestSites/AspNetCore_netcoreapp2.2_TestApp/Middleware/SimpleExceptionHandlerMiddleware.cs

**Comment by smatsson** [comment]
Did you manage to get any logs from the server?

**Comment by Unthred** [comment]
I haven't as yet I am afraid I was dragged off the project for a week or so. I am back on it now and will try tomorrow to get the logs.
The project I am working on is using asp.net and mvc 5 so will have to work out how to get global error handlers for it as I believe its not as easy as core.

I have however found that sometimes it does delete the files without errors, not often but sometimes. I suspect something is keeping the file open or some such.

Thanks

**Comment by Unthred** [comment]
So whilst I have not managed to get a proper error message I have found the cause. It was obviously me being a dufus!

So in this code to save the uploaded file
````
using (var output = new FileStream(localFilename, FileMode.Create))
{
   var uploadedFile = await file.GetContentAsync(token);
   Log.Debug($"---> Received uploaded file, CopyTo {localFilename}");
   uploadedFile.CopyTo(output);
   await output.FlushAsync(token);
   output.Close();
   uploadedFile.Close();   <-----
}
````
I had forgotten to close the file. 

Perhaps some error checking around the file deletion so it can give a better error message for idiot users like me? 

Thanks for all your help it works perfectly now

**Comment by smatsson** [comment]
Happy to hear that the issue was resolved! 

I tested your code locally and this is the exception that is thrown. I think that this should be enough to troubleshoot without giving away to much information to the client.

```csharp

fail: AspNetCore_netcoreapp2_2_TestApp.Middleware.SimpleExceptionHandlerMiddleware[0]
      The process cannot access the file 'C:\tusfiles\9c37cdab13424fb490f23f4769d1e4de' because it is being used by another process.
System.IO.IOException: The process cannot access the file 'C:\tusfiles\9c37cdab13424fb490f23f4769d1e4de' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at tusdotnet.Stores.InternalFileRep.Delete() in C:\Repos\tusdotnet\tusdotnet\Source\tusdotnet\Stores\InternalFileRep.cs:line 19
   at tusdotnet.Stores.TusDiskStore.<>c__DisplayClass15_0.<DeleteFileAsync>b__0() in C:\Repos\tusdotnet\tusdotnet\Source\tusdotnet\Stores\TusDiskStore.cs:line 199
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at tusdotnet.IntentHandlers.DeleteFileHandler.Invoke() in C:\Repos\tusdotnet\tusdotnet\Source\tusdotnet\IntentHandlers\DeleteFileHandler.cs:line 42
   at tusdotnet.TusProtocolHandlerIntentBased.Invoke(ContextAdapter context) in C:\Repos\tusdotnet\tusdotnet\Source\tusdotnet\TusProtocolHandlerIntentBased.cs:line 69
   at tusdotnet.TusCoreMiddleware.Invoke(HttpContext context) in C:\Repos\tusdotnet\tusdotnet\Source\tusdotnet\ExternalMiddleware\Core\TusCoreMiddleware.cs:line 71
   at AspNetCore_netcoreapp2_2_TestApp.Middleware.SimpleExceptionHandlerMiddleware.Invoke(HttpContext context) in C:\Repos\tusdotnet\tusdotnet\Source\TestSites\AspNetCore_netcoreapp2.2_TestApp\Middleware\SimpleExceptionHandlerMiddleware.cs:line 24
```

**Comment by Unthred** [comment]
Sorry for the late reply. I completely agree if I received that error I would have known immediately where to look for the error but the error I got was (500) Internal server error on deleting files. 
I am not sure why I did not get the same error as you.

**Comment by smatsson** [comment]
The output shown above is from my app's exception handler that I linked to a couple of comments ago. The response to the client is still 500 Internal Server Error as this is what happened.
